### ISSUE TITLE
Custom Label Format

### ISSUE THREAD

**Issue by Serternos** [brogan89/MinMaxSlider#9]
I would like to suggest adding support to override the way the labels are generated, with a custom "ToString" method, so if for example the values represent IDs, the actual objects name could be displayed as text

**Comment by brogan89** [comment]
Interesting... yeah I'm not really sure that would be in scope. It sounds a bit too custom to me.
However, I could make the `UpdateText()` method and virtual method so you could override it and do whatever you want.
I haven't looked at this code in years, but I'll see what I can do. 
Thanks for the suggestion.

**Comment by brogan89** [comment]
I've added a delegate you can use for custom labels. I added a demo scene as well to show the use case. Hope that helps 👍

**Comment by Serternos** [comment]
Thank you for implementing this! I actually played around with your code
locally and also ended up using a delegate, but doing so breaks the idea of
using a package, thats why i thought it would be nicer to have it as a
standard feature. So thanks for solving it :)

brogan89 ***@***.***> schrieb am Do., 19. Okt. 2023, 22:38:
